name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      api-image:
        description: "API-IMAGE URI"
        required: true
      transcript-image:
        description: "TRANSCRIPT-IMAGE URI"
        required: true
      region:
        description: "Region"
        default: "us-east-1"
        required: false

jobs:
  pack-deploy:
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/uat
      refs/heads/prod
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Extract Branch Name
        id: extract-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Update environment files UAT
        if: ${{ steps.extract-branch.outputs.branch == 'uat' }}
        run: aws s3 sync s3://environment-files-qa s3://environment-files-uat --metadata-directive REPLACE --cache-control 'max-age=86400,must-revalidate,public' --delete

      - name: Update environment files PROD
        if: ${{ steps.extract-branch.outputs.branch == 'prod' }}
        run: aws s3 sync s3://environment-files-uat s3://environment-files-prod --metadata-directive REPLACE --cache-control 'max-age=86400,must-revalidate,public' --delete

      - name: Set New API Image to Amazon ECS Task Definition
        id: api-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./.github/workflows/task-definition-${{ steps.extract-branch.outputs.branch  }}.json
          container-name: prp-be-container-${{ steps.extract-branch.outputs.branch }}
          image: ${{ github.event.inputs.api-image }}
      - name: Update Amazon ECS Cluster API Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.api-task-def.outputs.task-definition }}
          service: prp-be-srv-${{ steps.extract-branch.outputs.branch }}
          cluster: prp-cluster-${{ steps.extract-branch.outputs.branch }}
          wait-for-service-stability: true

      - name: Set New Transcript Service Image to Amazon ECS Task Definition
        id: transcript-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./.github/workflows/transcript-task-definition-${{ steps.extract-branch.outputs.branch }}.json
          container-name: prp-transcript-container-${{ steps.extract-branch.outputs.branch }}
          image: ${{ github.event.inputs.transcript-image }}
      - name: Update Amazon ECS Cluster Transcript Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.transcript-task-def.outputs.task-definition }}
          service: prp-transcript-srv-${{ steps.extract-branch.outputs.branch }}
          cluster: prp-cluster-${{ steps.extract-branch.outputs.branch }}
          wait-for-service-stability: true
