name: Manual Lambdas Deployment

on:
  workflow_dispatch:
    inputs:
      region:
        description: "Region"
        default: "us-east-1"
        required: false

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    needs: [pack-deploy]
    env:
      work-dir: ./src/AWS/Lambdas/UploadExhibitLambda
    if: contains('
      refs/heads/prod
      refs/heads/uat
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: check user permission
        uses: 74th/workflow-permission-action@1.0.0
        with:
          users: ${{ secrets.USERS_ALLOWED_DEPLOY_UAT_PROD }}
      - name: Extract Branch Name
        id: extract-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - run: dotnet tool install --global Amazon.Lambda.Tools --version 5.1.4
      - name: Update lambda function for upload exhibits UAT env
        working-directory: ${{ env.work-dir }}
        if: ${{ steps.extract-branch.outputs.branch == 'uat' }}
        run: dotnet lambda deploy-function --function-name UploadExhibitUAT
      - name: Update lambda function for upload exhibits PROD
        working-directory: ${{ env.work-dir }}
        if: ${{ steps.extract-branch.outputs.branch == 'prod' }}
        run: dotnet lambda deploy-function --function-name UploadExhibitProd
