name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'IMAGE:TAG'
        required: true

jobs:
  pack-deploy:
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/uat
      refs/heads/prod
      ', github.ref)
    steps:
    - uses: actions/checkout@v2
    - name: Extract Branch Name
      id: extract-branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Set New Image to Amazon ECS Task Definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./.github/workflows/task-definition-${{ steps.extract-branch.outputs.branch }}.json
        container-name: prp-be-container-${{ steps.extract-branch.outputs.branch }}
        image: ${{ github.event.inputs.image }}
    - name: Update Amazon ECS Cluster Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: prp-be-srv-${{ steps.extract-branch.outputs.branch }}
        cluster: prp-cluster-${{ steps.extract-branch.outputs.branch }}
        wait-for-service-stability: true
