name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'uat'
      image:
        description: 'IMAGE:TAG'
        required: true

jobs:
  pack-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Replace ConnectionStrings in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "CONNECTION_STRING"
        replace: "${{ secrets.CONNECTIONSTRING_UAT }}"
        exclude: "^$"
  
    - name: Replace Cognito Secret Access Key in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "SECRET_ACCESS_KEY"
        replace: "${{ secrets.COGNITOCONFIG_SECRETACCESSKEY_UAT }}"
        exclude: "^$"

    - name: Replace Cognito Access Key in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "ACCESS_KEY"
        replace: "${{ secrets.COGNITOCONFIG_ACCESSKEY_UAT }}"
        exclude: "^$"
    
    - name: Replace Cognito Client ID in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "CLIENT_ID"
        replace: "${{ secrets.COGNITOCONFIG_CLIENTID_UAT }}"
        exclude: "^$"
    
    - name: Replace Cognito User Pool in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "USER_POOL_ID"
        replace: "${{ secrets.COGNITOCONFIG_USERPOOLID_UAT }}"
        exclude: "^$"
    
    - name: Replace Cognito Authority in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "AUTHORITY"
        replace: "${{ secrets.COGNITOCONFIG_AUTHORITY_UAT }}"
        exclude: "^$"
    
    - name: Replace Twilio AccountSid in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "TWILIO_ACCOUNTSID"
        replace: "${{ secrets.TWILIOCONFIG_ACCOUNTSID_QA }}"
        exclude: "^$"
    
    - name: Replace Twilio AccountSid in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "TWILIO_AUTHTOKEN"
        replace: "${{ secrets.TWILIOCONFIG_AUTHTOKEN_QA }}"
        exclude: "^$"
    
    - name: Replace Twilio ApiKeySID in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "TWILIO_APIKEYSID"
        replace: "${{ secrets.TWILIOCONFIG_APIKEYSID_QA }}"
        exclude: "^$"

    - name: Replace Twilio ApiKeySecret in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "TWILIO_APIKEYSECRET"
        replace: "${{ secrets.TWILIOCONFIG_APIKEYSECRET_QA }}"
        exclude: "^$"

    - name: Replace Twilio S3DestinationKey in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "TWILIO_DESTINATION_KEY"
        replace: "${{ secrets.SERVICE_ACCOUNT_ACCESS_KEY_QA }}"
        exclude: "^$"

    - name: Replace Twilio S3DestinationSecret in QA task definition
      uses: jacobtomlinson/gha-find-replace@master
      with:
        include: 'task-definition-qa.json'
        find: "TWILIO_DESTINATION_SECRET"
        replace: "${{ secrets.SERVICE_ACCOUNT_SECRET_ACCESS_KEY_QA }}"
        exclude: "^$"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Set New Image to Amazon ECS Task Definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./.github/workflows/task-definition-qa.json
        container-name: prp-be-container-${{ github.event.inputs.environment }}
        image: ${{ github.event.inputs.image }}
    - name: Update Amazon ECS Cluster Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: prp-be-srv-${{ github.event.inputs.environment }}
        cluster: prp-cluster-${{ github.event.inputs.environment }}
        wait-for-service-stability: true
