name: Manual Deployment NonProd

on:
  workflow_dispatch:
    inputs:
      api-image:
        description: "API-IMAGE:TAG"
        required: true
      transcript-image:
        description: "TRANSCRIPT-IMAGE:TAG"
        required: true

jobs:
  pack-deploy-api:
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/qa
      refs/heads/performance
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Extract Branch Name
        id: extract-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update environment files
        run: aws s3 sync s3://environment-files-qa s3://environment-files-${{ steps.extract-branch.outputs.branch }} --metadata-directive REPLACE --cache-control 'max-age=86400,must-revalidate,public' --delete

      - name: Set New API Image to Amazon ECS Task Definition
        id: api-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./.github/workflows/task-definition-${{ steps.extract-branch.outputs.branch }}.json
          container-name: prp-be-container-${{ steps.extract-branch.outputs.branch }}
          image: ${{ github.event.inputs.api-image }}
      - name: Update Amazon ECS Cluster Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.api-task-def.outputs.task-definition }}
          service: prp-be-srv-${{ steps.extract-branch.outputs.branch }}
          cluster: prp-cluster-nonprod
          wait-for-service-stability: true

  pack-deploy-transcript:
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/qa
      refs/heads/performance
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Extract Branch Name
        id: extract-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set New Transcript Service Image to Amazon ECS Task Definition
        id: transcript-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./.github/workflows/transcript-task-definition-${{ steps.extract-branch.outputs.branch }}.json
          container-name: prp-transcript-container-${{ steps.extract-branch.outputs.branch }}
          image: ${{ github.event.inputs.transcript-image }}
      - name: Update Amazon ECS Cluster Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.transcript-task-def.outputs.task-definition }}
          service: prp-transcript-srv-${{ steps.extract-branch.outputs.branch }}
          cluster: prp-cluster-nonprod
          wait-for-service-stability: true
