name: Static analysis code
on:
  push:
    branches:
      - develop
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: highbyte/sonarscan-dotnet@1.0.2
        with:
          sonarProjectKey: prp-be
          sonarProjectName: prp-be
          sonarHostname: https://sonarqube.prdevelopment.net/
          dotnetBuildArguments: ./src/PrecisionReporters.Platform/PrecisionReporters.Platform.sln
          dotnetTestArguments: ./src/PrecisionReporters.Platform/PrecisionReporters.Platform.sln --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarOrganization: default-organization
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="./src/PrecisionReporters.Platform/PrecisionReporters.Platform.UnitTests/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
